# Generated by Django 5.0.4 on 2024-04-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=45, verbose_name='marca del carrro')),
                ('sucursal', models.CharField(max_length=45, verbose_name='localidad de llegada')),
                ('aspirante', models.CharField(max_length=100, verbose_name='aspirante al vehiculo')),
            ],
        ),
    ]
